[application]

# App (Project) Name
name = "moonlight"

out_dir = "docs"

[web.app]

# HTML title tag content
title = "moonlight"

base_path = "moonlight"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
